// Segments are parts of object-centric sentences.
function getRandomItem(list) {
	return list[Math.floor(Math.random()*list.length)];
}

// A random number between a range 
function getRandomRange(min, max) {
    return Math.random() * (max - min) + min;
}

// Splices a string
function spliceSlice(str, index, count, add) {
  return str.slice(0, index) + add + str.slice(index + count);
}

conditionals = new Array('then', 'but', 'and', 'or');
reflections = new Array('is', 'was', 'will be', 'be');
descriptions = new Array('red', 'bloated', 'gay', 'sweaty');
objects = new Array(
	'Gypsy curse',
	'moment of silence',
	'sausage festival',
	'honest cop with nothing left to lose',
	'Famine',
	'Flesh-eating bacteria',
	'Flying sex snakes',
//	'Sexting',
	'Shapeshifters',
	'Porn stars',
	'72 virgins',
//	'drive-by shooting',
	'time travel paradox',
	'Authentic Mexican cuisine',
	'Bling',
	'Consultants',
	'Crippling debt',
	'Daddy issues',
	'Donald Trump Seal of Approval™',
//	'Dropping a chandelier on your enemies and riding the rope up',
	'Former President George W. Bush',
	'Full frontal nudity',
	'Hormone injections',
//	'Laying an egg',
//	'Getting naked and watching Nickelodeon',
//	'Pretending to care',
	'Public ridicule',
//	'Sharing needles',
	'Boogers',
	'inevitable heat death of the universe',
	'miracle of childbirth',
	'Rapture',
//	'Whipping it out',
	'White privilege',
	'Wifely duties',
	'Hamburglar',
	'AXE Body Spray',
	'Blood of Christ',
//	'Horrifying laser hair removal accidents',
	'BATMAN',
	'Agriculture',
	'robust mongoloid',
	'Natural selection',
	'Coat hanger abortions',
//	'Eating all of the cookies before the AIDS bake-sale',
	'Michelle Obama\'s arms',
	'World of Warcraft',
//	'Swooping',
	'Obesity',
	'homoerotic volleyball montage',
	'Lockjaw',
	'mating display',
	'Testicular torsion',
	'All-you-can-eat shrimp for $4.99',
	'Domino\'s™ Oreo™ Dessert Pizza',
	'Kanye West',
	'Hot cheese',
	'Raptor attacks',
//	'Taking off your shirt',
	'Smegma',
	'Alcoholism',
	'middle-aged man on roller skates',
	'Care Bear Stare',
//	'Bingeing and purging',
	'Oversized lollipops',
	'Self-loathing',
	'Children on leashes',
	'Half-assed foreplay',
	'Holy Bible',
	'German dungeon porn',
//	'Being on fire',
	'Teenage pregnancy',
	'Gandhi',
//	'Leaving an awkward voicemail',
	'Uppercuts',
	'Customer service representatives',
	'erection that lasts longer than four hours',
	'My genitals',
//	'Picking up girls at the abortion clinic',
	'Science',
//	'Not reciprocating oral sex',
	'Flightless birds',
	'good sniff',
//	'Waterboarding',
	'balanced breakfast',
	'Historically black colleges',
//	'Actually taking candy from a baby',
	'Make-A-Wish Foundation',
	'clandestine butt scratch',
	'Passive-aggressive Post-it notes',
	'Chinese gymnastics team',
//	'Switching to Geico',
//	'Peeing a little bit',
	'Home video of Oprah sobbing into a Lean Cuisine',
	'Nocturnal emissions',
	'Jews',
	'My humps',
	'Powerful thighs',
//	'Winking at old people',
	'Mr. Clean, right behind you',
	'gentle caress of the inner thigh',
	'Sexual tension',
	'forbidden fruit',
	'Skeletor',
	'Fancy Feast',
//	'Being rich',
	'Sweet, sweet vengeance',
	'Republicans',
	'gassy antelope',
	'Natalie Portman',
//	'Copping a feel',
	'Kamikaze pilots',
	'Sean Connery',
	'homosexual agenda',
	'hardworking Mexican',
	'falcon with a cap on its head',
	'Altar boys',
	'Kool-Aid Man',
//	'Getting so angry that you pop a boner',
	'Free samples',
	'big hoopla about nothing',
//	'Doing the right thing',
	'Three-Fifths compromise',
	'Lactation',
	'World peace',
	'RoboCop',
	'Chutzpah',
	'Justin Bieber',
	'Oompa-Loompas',
//	'Inappropriate yodeling',
	'Puberty',
	'Ghosts',
	'asymmetric boob job',
	'Vigorous jazz hands',
//	'Fingering',
	'Glenn Beck catching his scrotum on a curtain hook',
	'GoGurt',
	'Police brutality',
	'John Wilkes Booth',
	'Preteens',
//	'Scalping',
	'Stifling a giggle at the mention of Hutus and Tutsis',
//	'"Tweeting."',
	'Darth Vader',
	'sad handjob',
	'Exactly what you\'d expect',
//	'Expecting a burp and vomiting on the floor',
	'Adderall™',
	'Embryonic stem cells',
	'Tasteful sideboob',
	'Panda sex',
	'icepick lobotomy',
	'Tom Cruise',
	'Mouth herpes',
	'Sperm whales',
	'Homeless people',
	'Third base',
	'Incest',
	'Pac-Man uncontrollably guzzling cum',
	'mime having a stroke',
	'Hulk Hogan',
	'God',
//	'Scrubbing under the folds',
	'Golden showers',
	'Emotions',
//	'Licking things to claim them as your own',
	'Pabst Blue Ribbon',
	'placenta',
	'Spontaneous human combustion',
	'Friends with benefits',
//	'Finger painting',
	'Old-people smell',
//	'Dying of dysentery',
	'My inner demons',
	'Super Soaker™ full of cat pee',
	'Aaron Burr',
//	'Cuddling',
	'chronic',
	'Cockfights',
	'Friendly fire',
	'Ronald Reagan',
	'disappointing birthday party',
	'sassy black woman',
	'Mathletes',
	'tiny horse',
	'William Shatner',
//	'Riding off into the sunset',
	'M. Night Shyamalan plot twist',
	'Jew-fros',
	'Mutually-assured destruction',
	'Pedophiles',
	'Yeast',
//	'Grave robbing',
//	'Eating the last known bison',
	'Catapults',
	'Poor people',
//	'Forgetting the Alamo',
	'Hustle',
	'Force',
//	'Wiping her butt',
	'Intelligent design',
	'Loose lips',
	'AIDS',
	'Pictures of boobs',
	'Übermensch',
	'Sarah Palin',
	'American Gladiators',
//	'Getting really high',
	'Scientology',
	'Penis envy',
//	'Praying the gay away',
	'Frolicking',
	'midgets shitting into a bucket',
	'KKK',
	'Genghis Khan',
	'Crystal meth',
	'Serfdom',
	'Stranger danger',
	'Bop It™',
	'Shaquille O\'Neal\'s acting career',
	'Prancing',
	'Vigilante justice',
	'Overcompensation',
	'Pixelated bukkake',
	'lifetime of sadness',
	'Racism',
	'Dwarf tossing',
	'Sunshine and rainbows',
	'monkey smoking a cigar',
	'Flash flooding',
	'Lance Armstrong\'s missing testicle',
	'Dry heaving',
	'terrorists',
	'Britney Spears at 55',
	'Attitude',
//	'Breaking out into song and dance',
	'Leprosy',
	'Gloryholes',
	'Nipple blades',
	'heart of a child',
	'Puppies',
//	'Waking up half-naked in a Denny\'s parking lot',
	'Dental dams',
	'Toni Morrison\'s vagina',
	'taint',
//	'Active listening',
	'Ethnic cleansing',
	'Little Engine That Could',
	'invisible hand',
//	'Waiting ‘til marriage',
	'Unfathomable stupidity',
	'Euphoria™ by Calvin Klein',
	'Re-gifting',
	'Autocannibalism',
	'Erectile dysfunction',
	'My collection of high-tech sex toys',
	'Pope',
	'White people',
	'Tentacle porn',
	'Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts',
	'Too much hair gel',
	'Seppuku',
	'Same-sex ice dancing',
//	'Cheating in the Special Olympics',
	'Charisma',
	'Keanu Reeves',
	'Sean Penn',
	'Nickelback',
	'look-see',
//	'Pooping back and forth. Forever',
	'Menstruation',
	'Kids with ass cancer',
	'salty surprise',
	'South',
	'violation of our most basic human rights',
	'YOU MUST CONSTRUCT ADDITIONAL PYLONS',
//	'Being fabulous',
	'Necrophilia',
	'Centaurs',
	'Bill Nye the Science Guy',
	'Black people',
	'Chivalry',
	'Lunchables™',
	'Bitches',
	'profoundly handicapped',
	'Heartwarming orphans',
	'MechaHitler',
	'Fiery poops',
	'Another goddamn vampire movie',
	'Tangled Slinkys',
//	'true meaning of Christmas',
	'Estrogen',
	'zesty breakfast burrito',
//	'That thing that electrocutes your abs',
//	'Passing a kidney stone',
	'bleached asshole',
	'Michael Jackson',
	'Cybernetic enhancements',
	'Guys who don\'t call',
	'Smallpox blankets',
	'Masturbation',
	'Classist undertones',
	'Queefing',
//	'Concealing a boner',
	'Edible underpants',
	'Viagra',
	'Soup that is too hot',
	'Muhammad (Praise Be Unto Him)',
	'Surprise sex',
	'Five-Dollar Footlongs™',
//	'Drinking alone',
	'Dick fingers',
	'Multiple stab wounds',
//	'Soiling oneself',
	'Child abuse',
	'Anal beads',
	'Civilian casualties',
//	'Pulling out',
	'Robert Downey, Jr',
	'Horse meat',
	'really cool hat',
	'Kim Jong-il',
	'stray pube',
	'Jewish fraternities',
	'token minority',
	'Doin\' it in the butt',
//	'Feeding Rosie O\'Donnell',
//	'Teaching a robot to love',
	'can of whoop-ass',
	'windmill full of corpses',
	'Count Chocula',
//	'Wearing underwear inside-out to avoid doing laundry',
	'death ray',
	'glass ceiling',
	'cooler full of organs',
	'American Dream',
	'Keg stands',
	'When you fart and a little bit comes out',
	'Take-backsies',
	'Dead babies',
	'Foreskin',
	'Saxophone solos',
	'Italians',
	'fetus',
//	'Firing a rifle into the air while balls deep in a squealing hog',
	'Dick Cheney',
	'Amputees',
	'Eugenics',
	'My relationship status',
	'Christopher Walken',
	'Bees',
	'Harry Potter erotica',
	'College',
//	'Getting drunk on mouthwash',
	'Nazis',
	'8 oz. of sweet Mexican black-tar heroin',
	'Stephen Hawking talking dirty',
	'Dead parents',
	'Object permanence',
	'Opposable thumbs',
	'Racially-biased SAT questions',
	'Jibber-jabber',
	'Chainsaws for hands',
	'Nicolas Cage',
	'Child beauty pageants',
	'Explosions',
//	'Sniffing glue',
	'Glenn Beck being harried by a swarm of buzzards',
	'Repression',
	'Roofies',
	'My vagina',
	'Assless chaps',
	'murder most foul',
//	'Giving 110 percent',
	'Her Royal Highness, Queen Elizabeth II',
	'Trail of Tears',
//	'Being marginalized',
	'Goblins',
	'Hope',
	'Rev. Dr. Martin Luther King, Jr',
	'micropenis',
	'My soul',
	'hot mess',
	'Vikings',
	'Hot people',
	'Seduction',
	'Oedipus complex',
	'Geese',
	'Global warming',
	'New Age music',
	'Hot Pockets',
//	'Making a pouty face',
	'Vehicular manslaughter',
	'Women\'s suffrage',
	'defective condom',
	'Judge Judy',
	'African children',
	'Virginia Tech Massacre',
	'Barack Obama',
	'Asians who aren\'t good at math',
	'Elderly Japanese men',
//	'Exchanging pleasantries',
	'Heteronormativity',
//	'Parting the Red Sea',
	'Arnold Schwarzenegger',
	'Road head',
	'Spectacular abs',
	'Figgy pudding',
	'mopey zoo lion',
	'bag of magic beans',
	'Poor life choices',
	'My sex life',
	'Auschwitz',
	'snapping turtle biting the tip of your penis',
	'thermonuclear detonation',
	'clitoris',
	'Big Bang',
	'Land mines',
	'Friends who eat all the snacks',
	'Goats eating cans',
	'Dance of the Sugar Plum Fairy',
//	'Jerking off into a pool of children\'s tears',
	'Man meat',
	'Me time',
	'Underground Railroad',
	'Poorly-timed Holocaust jokes',
	'sea of troubles',
	'Lumberjack fantasies',
	'Morgan Freeman\'s voice',
	'Women in yogurt commercials',
	'Natural male enhancement',
//	'Being a motherfucking sorcerer',
	'Genital piercings',
	'Passable transvestites',
	'Sexy pillow fights',
	'Balls',
	'Grandma',
	'Friction',
	'Party poopers',
//	'Farting and walking away',
//	'Being a dick to children',
//	'Booby-trapping the house to foil burglars',
	'Tempur-Pedic Swedish Sleep System™',
//	'Dying',
	'Hurricane Katrina',
	'gays',
	'folly of man',
	'Men',
	'Amish',
	'Pterodactyl eggs',
	'Team-building exercises',
	'brain tumor',
	'Cards Against Humanity',
	'Fear itself',
	'Lady Gaga',
	'milk man',
	'foul mouth',
	'big black dick',
	'beached whale',
	'bloody pacifier',
	'crappy little hand',
	'low standard of living',
	'nuanced critique',
	'Panty raids',
	'passionate Latino lover',
	'rival dojo',
	'web of lies',
	'woman scorned',
	'Clams',
//	'Apologizing',
	'Appreciative snapping',
	'Neil Patrick Harris',
//	'Beating your wives',
//	'Being a dinosaur',
	'Shaft',
	'Bosnian chicken farmers',
	'Nubile slave boys',
	'Carnies',
//	'Coughing into a vagina',
	'Suicidal thoughts',
//	'Dancing with a broom',
//	'Deflowering the princess',
	'Dorito breath',
//	'Eating an albino',
	'Enormous Scandinavian women',
//	'Fabricating statistics',
//	'Finding a skeleton',
	'Gandalf',
	'Genetically engineered super-soldiers',
	'George Clooney\'s musk',
//	'Getting abducted by Peter Pan',
//	'Getting in her pants, politely',
	'Gladiatorial combat',
	'Good grammar',
	'Hipsters',
	'Historical revisionism',
	'Insatiable bloodlust',
	'Jafar',
	'Jean-Claude Van Damme',
	'Just the tip',
	'Mad hacky-sack skills',
//	'Leveling up',
//	'Literally eating shit',
//	'Making the penises kiss',
	'Media coverage',
	'Medieval Times Dinner and Tournament',
	'Moral ambiguity',
	'My machete',
	'One thousand Slim Jims',
	'Ominous background music',
//	'Overpowering your father',
//	'Pistol-whipping a hostage',
	'Quiche',
	'Quivering jowls',
	'Revenge fucking',
//	'Ripping into a man\'s chest and pulling out his still-beating heart',
	'Ryan Gosling riding in on a white horse',
	'Santa Claus',
	'Scrotum tickling',
	'Sexual humiliation',
	'Sexy Siamese twins',
	'Slow motion',
	'Space muffins',
	'Statistically validated stereotypes',
	'Sudden Poop Explosion Disease',
	'boners of the elderly',
	'economy',
	'Fanta girls',
	'Gulags',
	'harsh light of day',
	'hiccups',
	'shambling corpse of Larry King',
	'four arms of Vishnu',
//	'Being a busy adult with many important things to do',
//	'Tripping balls',
	'Words, words, words',
	'Zeus\'s sexual appetites.'
);
sources = new Array('I', 'we');
actions = new Array('shank', 'love', 'cuttle');
emotives = new Array('angry', 'happy', 'not sure', 'confused');
possessors = new Array('my', 'your', 'our', 'his', 'her', 'its', 'the', 'a');
meanings = new Array('swiftly', 'stupidly');
punctuations = new Array('.', '...', '!', '?', '!!!', '?!?');
faces = new Array(':)', ':(', ':D', ':3', '<3', 'D:', ':C', 'C:', ':L', ':o', ':O', ':P', '.___.', '-___-', '-___-\'');
influencers = new Array('uhhh', 'come on', 'guys', 'yo', 'yes', 'well');
singularEmotiveActions = new Array('am', 'can be', 'will be', 'shall be', 'might be', 'should be', 'could be', 'would be');
pluralEmotiveActions = new Array('can be', 'will be', 'shall be', 'might be', 'are', 'should be', 'could be', 'would be');
modalActions = new Array('can', 'will', 'shall', 'might', 'should', 'could', 'would');


function speak(segments, statements) {
	segments = segments || [
        '%s %a %p? %o',
        '%s %v %e',
        '%p? %o %r? %d',
        '%p %o %r %o',
        '%a me, %o',
        '%a %o',
        '%m %a %p %d %o'
    ];

    statements = statements || [
        'if %seg, %c %seg',
        '%seg...? %seg',
        'should %s %a %p? %o %c %m %a %p %d %o',
        '%i, %seg',
        '%seg',
        //'%t %s %seg',
        '%seg, %i',
        '%s %v %e, %c? %seg',
        '%s %t %m? %a %o',
        '%o'
    ];

    var statement = getRandomItem(statements);

    // Fill in all segments
    while(statement.search('%seg') != -1) {
    	statement = statement.split('%seg').join(getRandomItem(segments));
    }
    console.log(statement);
    var position = statement.search('%');
    while(position != -1) {
    	var cursor = position + 1,
    		symbol = '',
    		word = '',
    		code = statement.charCodeAt(cursor);

    	while((code >= 97 && code <= 122) || code == 63) {
    		if(code == 63) {
    			if(getRandomRange(0, 100) > 80) {
    				// Reject the symbol
    				symbol = '';
    				break;
    			}
    		} else {
    			symbol += statement[cursor];
    		}
    		cursor += 1;
    		code = statement.charCodeAt(cursor);
    	}

    	switch(symbol) {
    		// Conditional (then, but, and, or)
    		case 'c': word = getRandomItem(conditionals); break;
    			
    		// Reflection (is, was, will be)
    		case 'r': word = getRandomItem(reflections); break;
    		
    		// Description (adjectives)
    		case 'd': word = getRandomItem(descriptions); break;
    		
    		// Object (nouns)
    		case 'o': word = getRandomItem(objects); break;
    		
    		//  Source (I, we, she, he, it)
    		case 's': word = getRandomItem(sources); break;
    		
    		// Action (verbs)
    		case 'a': word = getRandomItem(actions); break;
    		
    		// Emotive (angry, happy, not sure, confused, etc.)
    		case 'e': word = getRandomItem(emotives); break;
    		
    		// Possessor (my, your, our, his, her, its, the, a)
    		case 'p': word = getRandomItem(possessors); break;
    		
    		// Meaning (adverb)
    		case 'm': word = getRandomItem(meanings); break;
    		
    		// Influencer (Uhhh, Come on, Guys, Yo, Yes, Well, No etc.)
    		case 'i': word = getRandomItem(influencers); break;
    		
    		// Emotive Action (am, can, will, shall, might, are, should, could, would)
    		case 'v':
    			var previous = position - 3;
    			if(previous < 0) {
    				previous = 0;
    			}
    			console.log([previous, statement.substr(previous, 3), statement.substr(previous, 3).search('we')]);
    			if(statement.substr(previous, 3).search('we') == -1) {
    				word = getRandomItem(singularEmotiveActions); break;	
    			} else {
    				word = getRandomItem(pluralEmotiveActions); break;
    			}
    		
    		// Modal Action (can, will, shall, might, are, should, could, would)
    		case 't':
    			word = getRandomItem(modalActions); break;
    		
    		default: continue;
    	}

    	statement = spliceSlice(statement, position, cursor - position, word);
    	position = statement.search('%');
    }
    return statement + getRandomItem(punctuations);
}
